name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: quddnddl35/oregano
          stage: main
          yaml: >
            name: oregano-react

            app: web

            options:
              nodeversion: "21"
              spa: true
              buildenv:
                - name: REACT_APP_KAKAO_MAP_KEY
                  value: //dapi.kakao.com/v2/maps/sdk.js?appkey=8f80c29372501ab918f32c6f4da8763f&libraries=services&autoload=false
                - name: REACT_APP_API_BASE_URL
                  value: https://port-0-oregano-lxfol2lf38345220.sel5.cloudtype.app/api
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: react
